### ISSUE TITLE
Momentary flash of content on load / submit Issue button does not work

### ISSUE THREAD

**Issue by david-mcafee** [svidgen/markboard-support#1]
First of all, this tool is AWESOME!! 

Two super minor (nitpick) items I saw: 1) the submit issue link on this repo's README does not work, and 2) when you first load `markboard.dev`, there's a momentary flash of content (e.g. "My Licenses | New Live Board") above the editor.

However, the editor itself works magically, and I plan to use this!

**Comment by svidgen** [comment]
Fixed the link. The other I'll look at in the next few days.

Thanks for giving this a look!

**Comment by svidgen** [comment]
Should be fixed.

Thanks for reporting it!
